name: Clean-up stale branches

on:
  schedule:
    - cron: '22 * * * *'
  push:
    branches:
      - 'main'

jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Run delete-old-branches-action
        uses: site-assist/action-helpers-housekeeping@master
        with:
          repo_token: ${{ github.token }}
          date: '1 minutes ago'
          dry_run: true
          delete_tags: true
          minimum_tags: 5
          extra_protected_branch_regex: main|master|mobile/*|mobile/**|test/haideti
          extra_protected_tag_regex: '^v.*'
          exclude_open_pr_branches: true